version: '3.4'

networks:
  backend:

services:
  companydb:
    container_name: company-db
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=sa@12345#
    networks:
        - backend
    ports:
        - 8001:1433
  companyservices.api:
    container_name: company-api
    image: ${DOCKER_REGISTRY-}companyservicesapi
    build:
      context: .
      dockerfile: CompanyServices.Api/Dockerfile
    networks:
        - backend
    ports:
        - 8002:80
    environment:
        - DB_HOST=companydb
        - DB_NAME=company
        - DB_SA_PASSWORD=sa@12345#
  jenistransactiondb:
    container_name: jenistransaksi-db
    image: mysql:8.1.0
    ports:
        - 8003:3305 
    networks:
        - backend
  jenistransactionservices:
    container_name: jenisTransaksi-api
    image: ${DOCKER_REGISTRY-}jenistransactionservices
    build:
      context: .
      dockerfile: JenisTransactionServices/Dockerfile
    networks:
        - backend
    ports:
        - 8004:80
    environment:
        - DB_HOST=jenistransactiondb
        - DB_NAME=dms_jenisTransaction
        - DB_ROOT_PASSWORD=sa@12345#

